---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: master
spec:
  serviceName: master
  replicas: 1
  selector:
    matchLabels:
      app: postgres-master
  template:
    metadata:
      labels:
        app: postgres-master
    spec:
      containers:
        - name: postgres-master
          image: postgres:16.3
          ports:
            - containerPort: 5432
          env:
          - name: POSTGRES_PASSWORD
            value: password
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
          args:
            - "-c"
            - "config_file=/config/postgresql.conf"
          volumeMounts:
            - name: master-volume
              mountPath: /var/lib/postgresql/data
            - name: config-volume
              mountPath: /config
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d
      volumes:  
        - name: config-volume
          configMap:
            name: postgres-config-map
        - name: init-script
          configMap:
            name: postgres-init-script
  volumeClaimTemplates:
    - metadata:
        name: master-volume
      spec:
        storageClassName: gp2
        accessModes: ["ReadWriteOncePod"]
        resources:
          requests:
            storage: 1Gi
